---
- name: create a non-root user with sudo rights
  hosts: all
  remote_user: user
  vars_files:
  - vars.yml
  tasks:

  - name: update aptitude cache
    raw: apt-get update

  - name: install python-apt for ansible
    raw: apt-get install python-apt

  - name: ensure a sudo group exists
    group: name=sudo state=present

  - name: ensure users in the sudo group can sudo passwordless
    lineinfile: "dest=/etc/sudoers state=present
                 regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'
                 validate='visudo -cf %s'"

  - name: create the user account
    user: name={{ username }} state=present
          append=true groups=sudo

  - name: install your public key
    authorized_key: user={{ username }} state=present
                    key="{{ lookup('file', local_ssh_pubkey) }}"

  - name: some basic apt stuff
    apt: pkg=git state=installed

- name: install devstack on controllers
  hosts: controllers
  vars_files:
  - vars.yml
  remote_user: "{{ username }}"
  tasks:

  - name: clone devstack
    git: repo=https://github.com/openstack-dev/devstack.git
         dest=~/devstack
         version={{ branch }}

  - name: devstack local.conf
    template: src=templates/controller-local.conf
              dest=~/devstack/local.conf

  - name: stack it
    command: chdir=~/devstack ./stack.sh
    ignore_errors: yes

- name: install devstack on computes
  hosts: computes
  vars_files:
  - vars.yml
  remote_user: "{{ username }}"
  tasks:

  - name: clone devstack
    git: repo=https://github.com/openstack-dev/devstack.git
         dest=~/devstack
         version={{ branch }}

  - name: devstack local.conf
    template: src=templates/compute-local.conf
              dest=~/devstack/local.conf

  - name: stack it
    command: chdir=~/devstack ./stack.sh
    ignore_errors: yes

- name: update controllers' compute host discovery
  hosts: controllers
  vars_files:
  - vars.yml
  remote_user: "{{ username }}"
  tasks:

  - name: run discover_hosts.sh
    command: chdir=~/devstack ./tools/discover_hosts.sh
    ignore_errors: yes